mv abbrevs.zsh.txt abbrevs.zsh
mv aliases.zsh.txt aliases.zsh
mv auto.zsh.txt auto.zsh
mv completion.zsh.txt completion.zsh
mv funcs.zsh.txt funcs.zsh
mv fzf.zsh.txt fzf.zsh
mv git_prompt.zsh.txt git_prompt.zsh
mv highlight.zsh.txt highlight.zsh
mv history_file.zsh.txt history_file.zsh
mv history.zsh.txt history.zsh
mv misc.zsh.txt misc.zsh
mv open.zsh.txt open.zsh
mv options.zsh.txt options.zsh
mv paths.zsh.txt paths.zsh
mv prompt.zsh.txt prompt.zsh
mv vi.zsh.txt vi.zsh
